name: gcloud
version: 0.10.0
description: >-
  High level idiomatic Dart API for Google Cloud Storage, Pub-Sub and Datastore.
repository: https://github.com/dart-lang/labs/tree/main/pkgs/gcloud
issue_tracker: https://github.com/dart-lang/labs/issues?q=is%3Aissue+is%3Aopen+label%3Apackage%3Agcloud

topics:
 - cloud
 - gcp

environment:
  sdk: ^3.0.0

dependencies:
  _discoveryapis_commons: ^1.0.0
  googleapis: ^15.0.0
  http: '>=0.13.5 <2.0.0'
  meta: ^1.3.0
  retry: ^3.1.1

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  googleapis_auth: ^2.0.0
  http_parser: ^4.0.0
  mime: ^2.0.0
  test: ^1.17.5
