name: timezone
description: Time zone databases and time zone aware `DateTime`.
repository: https://github.com/srawlins/timezone
version: 0.10.2

environment:
  sdk: ^3.10.0

dependencies:
  http: ^1.6.0
  path: ^1.9.1

dev_dependencies:
  args: ^2.7.0
  dart_flutter_team_lints: ^3.5.2
  file: ^7.0.1
  glob: ^2.1.3
  logging: ^1.3.0
  test: ^1.28.0
