name: timezone
version: 0.7.1
description: Time zone database and time zone aware DateTime.
repository: https://github.com/srawlins/timezone
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  path: ^1.8.0
dev_dependencies:
  args: any
  file: ^6.0.0
  glob: ^2.0.0
  logging: any
  pedantic: ^1.10.0
  test: ^1.16.0
