name: package:io_file

permissions: read-all

on:
  # Run CI on pushes to the main branch, and on PRs against main.
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/io_file.yml'
      - 'pkgs/io_file/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/io_file.yml'
      - 'pkgs/io_file/**'
  schedule:
    - cron: '0 0 * * 0' # weekly

defaults:
  run:
    working-directory: pkgs/io_file

jobs:
  analyze_and_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c
        with:
          sdk: stable
      - run: dart pub get
      - run: dart analyze --fatal-infos
      - run: dart format --output=none --set-exit-if-changed .

  desktop-vm-test:
    strategy:
      fail-fast: false
      matrix:
        sdk: [stable, dev]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c
        with:
          sdk: ${{ matrix.sdk }}

      - run: dart test --test-randomize-ordering-seed=random --platform vm

  desktop-vm-benchmark:
    strategy:
      fail-fast: false
      matrix:
        sdk: [stable]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c
        with:
          sdk: ${{ matrix.sdk }}
      - run: dart pub get
      - name: ğŸª‘ Run benchmarks
        run: dart run benchmarks/read_as_bytes.dart

  ios-vm-test:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: pkgs/io_file/mobile_test
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: subosito/flutter-action@f2c4f6686ca8e8d6e6d0f28410eeef506ed66aff
        with:
          flutter-version: any
          channel: 'stable'
      - uses: futureware-tech/simulator-action@dab10d813144ef59b48d401cd95da151222ef8cd
        with:
          os: iOS
          os_version: '>=13.0'

      - run: |
          flutter pub get
          flutter test integration_test --test-randomize-ordering-seed=random

  web-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c
        with:
          sdk: stable

      - run: dart test --test-randomize-ordering-seed=random --platform chrome
