# A CI configuration to post comments to PRs.
#
# This workflow will have permissions to create comments on the PR even if the
# original workflow couldn't.

name: Comment on the pull request
permissions: read-all

on:
  workflow_run:
    workflows: 
      - Publish
      - Health
    types:
      - completed

jobs:
  upload:
    uses: dart-lang/ecosystem/.github/workflows/post_summaries.yaml@main
    permissions:
      pull-requests: write
