name: package:unix_api

permissions: read-all

on:
  # Run CI on pushes to the main branch, and on PRs against main.
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/unix_api.yml'
      - 'pkgs/unix_api/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/unix_api.yml'
      - 'pkgs/unix_api/**'
  schedule:
    - cron: '0 0 * * 0' # weekly

defaults:
  run:
    working-directory: pkgs/unix_api

jobs:
  analyze_and_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c
      - run: dart pub get
      - run: dart analyze --fatal-infos
      - run: dart format --output=none --set-exit-if-changed .

  check-generation:
    # Verify that the generated code is up-to-date. Every platform/arch should
    # generate the same API bindings.
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c
      - run: dart pub get
      - run: dart run tool/generate.dart
      - run: git diff --exit-code

  desktop-vm-test:
    strategy:
      fail-fast: false
      matrix:
        sdk: [stable, beta]
        os: [macos-latest, ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c
        with:
          sdk: ${{ matrix.sdk }}
      - run: dart test --reporter=failures-only --test-randomize-ordering-seed=random --platform vm
